### ISSUE TITLE
Stop using Reakit `<Composite>` for the station picker

### ISSUE THREAD

**Issue by idreyn** [transitmatters/regional-rail-explorer#66]
I originally used this component because I wanted good arrow key support in this menu — but I'm finding:

1. It's slow
2. It's forcing us to write unidiomatic React — checking `data-id` attributes on divs!
3. It actually breaks keyboard users' expectations of being able to _tab_ through the list.

So let's remove it — probably we embed an `onClick` handler inside of `<StationName>` and, when that's available, use a Reakit `<Button>` inside of `<StationName>`? There may also be some aria attributes we can add to this component to retain the semantic flavor of "a list of selectable items".

Also note that when we make this change we should make the `<StationName>` tooltip focusable with:

```scss
  .infillStatus:hover .tooltipText,
  .infillStatus:focus .tooltipText {
      visibility: visible;
  }
```
